#!/usr/bin/env python3

"""
rennda_game_builder.py (V2 - コントローラバグ修正版)
(c) 2024 (Generated by AI for demonstration)

このスクリプトは、ファミコン (NES) エミュレータで動作する
「連打測定ゲーム」の .nes ROM ファイルを生成します。

修正点:
- コントローラ読み取りロジックを修正 (Aボタンが Bit 0 に)
- コントローラトリガー判定のロジックを修正
"""

import sys
import os

# --- 定数 ---
CHR_ROM_SIZE = 8192    # 8KB (フォント、UI用)
PRG_ROM_SIZE = 16384   # 16KB

# --- 1. CHR ROM (グラフィック) 生成 ---

def generate_font_chr():
    """
    ゲームに必要なフォント (8x8, 2bpp) を CHR ROM として生成する。
    """
    print("ステップ 1: CHR ROM (フォント) を生成中...")
    chr_data = bytearray(CHR_ROM_SIZE) # 8KB を 0 で初期化

    def pixels_to_tile(pixels):
        plane0 = bytearray(8)
        plane1 = bytearray(8)
        for y in range(8):
            byte0 = 0
            byte1 = 0
            for x in range(8):
                color = pixels[y * 8 + x]
                low_bit = (color & 1)
                high_bit = (color >> 1) & 1
                byte0 |= (low_bit << (7 - x))
                byte1 |= (high_bit << (7 - x))
            plane0[y] = byte0
            plane1[y] = byte1
        return plane0 + plane1

    def write_tile(index, pixels):
        offset = index * 16
        if offset + 16 > CHR_ROM_SIZE:
            raise IndexError(f"CHR ROM インデックス {index} が範囲外です。")
        chr_data[offset : offset + 16] = pixels_to_tile(pixels)

    # --- フォントデータの定義 (インデックス 0-9 に '0'-'9') ---
    font_0 = [0,3,3,3,3,3,0,0, 3,3,0,0,0,3,3,0, 3,0,3,0,0,0,3,0, 3,0,0,3,0,0,3,0, 3,0,0,0,3,0,3,0, 3,0,3,0,0,3,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_1 = [0,0,0,3,3,0,0,0, 0,0,3,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_2 = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,3,0, 0,0,0,0,0,3,0,0, 0,0,0,0,3,0,0,0, 0,0,3,0,0,0,0,0, 3,3,3,3,3,3,3,0, 0,0,0,0,0,0,0,0]
    font_3 = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,3,0, 0,0,0,3,3,3,0,0, 0,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_4 = [0,0,0,0,3,3,0,0, 0,0,0,3,0,3,0,0, 0,0,3,0,0,3,0,0, 0,3,0,0,0,3,0,0, 3,3,3,3,3,3,3,0, 0,0,0,0,0,3,0,0, 0,0,0,0,0,3,0,0, 0,0,0,0,0,0,0,0]
    font_5 = [3,3,3,3,3,3,3,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_6 = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_7 = [3,3,3,3,3,3,3,0, 0,0,0,0,0,0,3,0, 0,0,0,0,0,3,0,0, 0,0,0,0,3,0,0,0, 0,0,0,3,0,0,0,0, 0,0,3,0,0,0,0,0, 0,0,3,0,0,0,0,0, 0,0,0,0,0,0,0,0]
    font_8 = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_9 = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,3,0, 0,0,0,0,0,0,3,0, 0,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    
    write_tile(0, font_0)
    write_tile(1, font_1)
    write_tile(2, font_2)
    write_tile(3, font_3)
    write_tile(4, font_4)
    write_tile(5, font_5)
    write_tile(6, font_6)
    write_tile(7, font_7)
    write_tile(8, font_8)
    write_tile(9, font_9)

    # (インデックス 10 は空白タイル = 0)

    # (インデックス 11- はアルファベット)
    font_A = [0,0,3,3,3,0,0,0, 0,3,0,0,0,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,3,3,3,3,3,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,0,0]
    font_C = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_E = [3,3,3,3,3,3,3,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,3,3,3,3,3,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,3,3,3,3,3,3,0, 0,0,0,0,0,0,0,0]
    font_I = [0,3,3,3,3,3,3,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,3,3,3,3,3,3,0, 0,0,0,0,0,0,0,0]
    font_M = [3,0,0,0,0,0,3,0, 3,3,0,0,0,3,3,0, 3,0,3,0,3,0,3,0, 3,0,0,3,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,0,0]
    font_N = [3,0,0,0,0,0,3,0, 3,3,0,0,0,0,3,0, 3,0,3,0,0,0,3,0, 3,0,0,3,0,0,3,0, 3,0,0,0,3,0,3,0, 3,0,0,0,0,3,3,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,0,0]
    font_O = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_P = [3,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,3,3,3,3,3,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 3,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0]
    font_R = [3,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,3,3,3,3,3,0,0, 3,0,0,0,3,0,0,0, 3,0,0,0,0,3,0,0, 3,0,0,0,0,0,3,0, 0,0,0,0,0,0,0,0]
    font_S = [0,3,3,3,3,3,0,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,0,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    font_T = [3,3,3,3,3,3,3,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,0,0,0,0,0]
    font_U = [3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 3,0,0,0,0,0,3,0, 0,3,3,3,3,3,0,0, 0,0,0,0,0,0,0,0]
    
    font_colon = [0,0,0,0,0,0,0,0, 0,0,3,3,0,0,0,0, 0,0,3,3,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,3,3,0,0,0,0, 0,0,3,3,0,0,0,0, 0,0,0,0,0,0,0,0]
    font_exclam = [0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,3,3,0,0,0, 0,0,0,0,0,0,0,0]
    
    # マッピング (タイルインデックス)
    # 0-9: '0'-'9'
    # 10: ' ' (空白)
    # 11: 'A'
    # 12: 'C'
    # 13: 'E'
    # 14: 'I'
    # 15: 'M'
    # 16: 'N'
    # 17: 'O'
    # 18: 'P'
    # 19: 'R'
    # 20: 'S'
    # 21: 'T'
    # 22: 'U'
    # 23: ':'
    # 24: '!'
    
    write_tile(11, font_A)
    write_tile(12, font_C)
    write_tile(13, font_E)
    write_tile(14, font_I)
    write_tile(15, font_M)
    write_tile(16, font_N)
    write_tile(17, font_O)
    write_tile(18, font_P)
    write_tile(19, font_R)
    write_tile(20, font_S)
    write_tile(21, font_T)
    write_tile(22, font_U)
    write_tile(23, font_colon)
    write_tile(24, font_exclam)
    
    return chr_data

# --- 2. PRG ROM (プログラム) 生成 ---

def generate_prg_rom():
    """
    ゲームロジックの 6502 マシン語 (16KB) を生成する。
    """
    print("ステップ 2: PRG ROM (ゲームロジック) を生成中...")
    
    prg_rom = bytearray(PRG_ROM_SIZE) # 16KB を 0 で初期化

    # --- PRG ROM データ (テキストなど) ---
    # $E000 から配置
    
    # "PRESS A TO START" (16文字)
    text_title = [18, 19, 13, 20, 20, 10, 11, 10, 21, 17, 10, 20, 21, 11, 19, 21]
    # "COUNT:" (6文字)
    text_count = [12, 17, 22, 16, 21, 23]
    # "TIME:" (5文字)
    text_time = [21, 14, 15, 13, 23]
    # "TIME UP!!" (9文字)
    text_timeup = [21, 14, 15, 13, 10, 22, 18, 24, 24]

    data_offset = 0xE000 - 0xC000 # 0x2000
    prg_rom[data_offset : data_offset + len(text_title)] = bytearray(text_title)
    prg_rom[data_offset + 0x20 : data_offset + 0x20 + len(text_count)] = bytearray(text_count)
    prg_rom[data_offset + 0x40 : data_offset + 0x40 + len(text_time)] = bytearray(text_time)
    prg_rom[data_offset + 0x60 : data_offset + 0x60 + len(text_timeup)] = bytearray(text_timeup)
    
    # --- 6502 コード (アセンブリ) ---
    # $C000 から配置
    
    # Zero Page 変数 (アドレス)
    # $00 = GameState (0:Title, 1:Countdown, 2:Game, 3:Result)
    # $01 = FrameCounter (60fps)
    # $02 = Timer (Seconds, 10 -> 0)
    # $03 = RenndaCount_L (連打カウント Low)
    # $04 = RenndaCount_H (連打カウント High)
    # $05 = Controller_Raw (A=Bit0)
    # $06 = Controller_Trg (トリガー, 押した瞬間)
    # $07 = Controller_Old (1フレーム前)
    # $08 = TempA
    # $09 = TempX
    # $0A = TempY
    # $0B = TempPtr_L
    # $0C = TempPtr_H
    # $0D = Digit (10進数変換用)
    
    code = [
        # --- $C000: Reset Handler ---
        0x78,        # SEI
        0xD8,        # CLD
        0xA2, 0xFF,  # LDX #$FF
        0x9A,        # TXS
        
        # PPU/APU 初期化
        0xA9, 0x00,  # LDA #$00
        0x8D, 0x00, 0x20,  # STA $2000 (NMI OFF)
        0x8D, 0x01, 0x20,  # STA $2001 (RENDER OFF)
        0x8D, 0x10, 0x40,  # STA $4010
        0x8D, 0x15, 0x40,  # STA $4015
        
        # VBlank 待ち (x2)
        0xAD, 0x02, 0x20,  # BIT $2002
        0x10, 0xFB,        # BPL
        0xAD, 0x02, 0x20,  # BIT $2002
        0x10, 0xFB,        # BPL

        # Zero Page 初期化
        0xA2, 0x00,  # LDX #$00
        0xA9, 0x00,  # LDA #$00
    #ClearZP:
        0x95, 0x00,  # STA $00,X
        0xE8,        # INX
        0xE0, 0x10,  # CPX #$10
        0xD0, 0xF9,        # BNE ClearZP
        
        # VRAM クリア ($2000-$23FF)
        0xA9, 0x20,  # LDA #$20
        0x8D, 0x06, 0x20,  # STA $2006
        0xA9, 0x00,
        0x8D, 0x06, 0x20,  # STA $2006
        0xA9, 0x10,  # LDA #$10 (空白)
        0xA2, 0x04,  # LDX #$04 (4 ページ)
    #ClearVRAM_Page:
        0xA0, 0x00,  # LDY #$00
    #ClearVRAM_Loop:
        0x8D, 0x07, 0x20,  # STA $2007
        0xC8,        # INY
        0xD0, 0xFB,  # BNE ClearVRAM_Loop
        0xCA,        # DEX
        0xD0, 0xF7,  # BNE ClearVRAM_Page
        
        # パレットのロード
        0xAD, 0x02, 0x20,
        0xA9, 0x3F,
        0x8D, 0x06, 0x20,
        0xA9, 0x00,
        0x8D, 0x06, 0x20,
        0xA9, 0x0F,  # BG (黒)
        0x8D, 0x07, 0x20,
        0xA9, 0x00,  # (暗灰)
        0x8D, 0x07, 0x20,
        0xA9, 0x10,  # (明灰)
        0x8D, 0x07, 0x20,
        0xA9, 0x30,  # 文字 (白)
        0x8D, 0x07, 0x20,
        
        # アトリビュートテーブル (パレット 0)
        0xA9, 0x23,
        0x8D, 0x06, 0x20,
        0xA9, 0xC0,
        0x8D, 0x06, 0x20,
        0xA9, 0x00,
        0xA0, 0x40,
    #ClearAttr_Loop:
        0x8D, 0x07, 0x20,
        0x88,        # DEY
        0xD0, 0xFB,  # BNE ClearAttr_Loop
        
        # NMI 有効化、BG ON
        0xA9, 0x80,  # LDA #%10000000 (NMI ON)
        0x8D, 0x00, 0x20,  # STA $2000
        0xA9, 0x0E,  # LDA #%00001110 (BG ON)
        0x8D, 0x01, 0x20,  # STA $2001
        
        0x58,        # CLI
        
    #InfiniteLoop: ($C093)
        0x4C, 0x93, 0xC0,  # JMP InfiniteLoop
        
        # --- $C100: NMI Handler (VBlank) ---
        0x48,        # PHA
        0x8A,        # TXA
        0x48,        # PHA
        0x98,        # TYA
        0x48,        # PHA
        
        # コントローラ読み取り
        0x20, 0x00, 0xC2,  # JSR ReadController ($C200)
        
        # ★★★ バグ修正 (トリガー計算) ★★★
        # Trg = Raw AND (NOT Old)
        0xA5, 0x07,  # LDA Controller_Old
        0x49, 0xFF,  # EOR #$FF (NOT Old)
        0x25, 0x05,  # AND Controller_Raw (AND Raw)
        0x85, 0x06,  # STA Controller_Trg
        0xA5, 0x05,  # LDA Controller_Raw
        0x85, 0x07,  # STA Controller_Old
        
        # --- ゲームロジックメイン ---
        0xA5, 0x00,  # LDA GameState
        0xC9, 0x00,  # CMP #$00 (Title)
        0xF0, 0x10,  # BEQ StateTitle
        0xC9, 0x01,  # CMP #$01 (Countdown)
        0xF0, 0x20,  # BEQ StateCountdown
        0xC9, 0x02,  # CMP #$02 (Game)
        0xF0, 0x40,  # BEQ StateGame
        0xC9, 0x03,  # CMP #$03 (Result)
        0xF0, 0x6A,  # BEQ StateResult
        0x4C, 0xEF, 0xC1,  # JMP NMI_End
        
    #StateTitle: ($C129)
        # "PRESS A TO START" 描画
        0x20, 0x00, 0xC3,  # JSR DrawTextTitle ($C300)
        
        # ★★★ バグ修正 (Aボタンは Bit 0) ★★★
        0xA5, 0x06,  # LDA Controller_Trg
        0x29, 0x01,  # AND #%00000001 (A ボタン)
        0xF0, 0x0E,  # BEQ Title_End (押されてない)
        
        # A が押された -> Countdown へ移行
        0xA9, 0x01,  # LDA #$01
        0x85, 0x00,  # STA GameState
        0x20, 0x80, 0xC2,  # JSR ClearVRAM_BG
        0xA9, 0x04,  # LDA #$04 (4 秒)
        0x85, 0x02,  # STA Timer
        0xA9, 0x00,  # LDA #$00
        0x85, 0x01,  # STA FrameCounter
    #Title_End:
        0x4C, 0xEF, 0xC1,  # JMP NMI_End
        
    #StateCountdown: ($C14B)
        0xE6, 0x01,  # INC FrameCounter
        0xA5, 0x01,  # LDA FrameCounter
        0xC9, 0x3C,  # CMP #60
        0x90, 0x14,  # BCC Countdown_End
        
        # 1秒経過
        0xA9, 0x00,
        0x85, 0x01,
        0xC6, 0x02,  # DEC Timer
        0xA5, 0x02,  # LDA Timer
        0xF0, 0x03,  # BEQ StartGame
        
        # カウントダウン描画 (Timer-1)
        0x38,
        0xE9, 0x01,
        0x20, 0x40, 0xC3,  # JSR DrawSingleDigit
        0x4C, 0xEF, 0xC1,  # JMP NMI_End

    #StartGame:
        0xA9, 0x02,
        0x85, 0x00,
        0x20, 0x80, 0xC2,
        0xA9, 0x0A,  # 10 秒
        0x85, 0x02,
        
    #Countdown_End:
        0x4C, 0xEF, 0xC1,  # JMP NMI_End
        
    #StateGame: ($C18D)
        # 描画
        0x20, 0x20, 0xC3,  # JSR DrawTextCount
        0x20, 0x30, 0xC3,  # JSR DrawTextTime
        0xA5, 0x04, 0x85, 0x09, 0xA5, 0x03, 0x85, 0x08,
        0x20, 0xA0, 0xC3,  # JSR DrawNumber (3桁)
        0xA9, 0x00, 0x85, 0x09, 0xA5, 0x02, 0x85, 0x08,
        0x20, 0xF0, 0xC3,  # JSR DrawNumber (2桁)
        
        # ★★★ バグ修正 (Aボタンは Bit 0) ★★★
        0xA5, 0x06,  # LDA Controller_Trg
        0x29, 0x01,  # AND #%00000001
        0xF0, 0x06,  # BEQ Game_NoRennda
        
        # 連打カウントアップ
        0xE6, 0x03,  # INC RenndaCount_L
        0xD0, 0x02,  # BNE Game_NoRennda
        0xE6, 0x04,  # INC RenndaCount_H
        
    #Game_NoRennda:
        # 1秒タイマー処理
        0xE6, 0x01,
        0xA5, 0x01,
        0xC9, 0x3C,
        0x90, 0x0B,  # BCC Game_End
        
        0xA9, 0x00,
        0x85, 0x01,
        0xC6, 0x02,
        0xA5, 0x02,
        0xF0, 0x03,  # BEQ GoToResult
    #Game_End:
        0x4C, 0xEF, 0xC1,  # JMP NMI_End
        
    #GoToResult:
        0xA9, 0x03,
        0x85, 0x00,
        0x20, 0x80, 0xC2,
        0x4C, 0xEF, 0xC1,  # JMP NMI_End
        
    #StateResult: ($C1F3)
        # 描画
        0x20, 0x60, 0xC3,  # JSR DrawTextTimeUp
        0x20, 0x20, 0xC3,  # JSR DrawTextCount
        0xA5, 0x04, 0x85, 0x09, 0xA5, 0x03, 0x85, 0x08,
        0x20, 0xA0, 0xC3,  # JSR DrawNumber (3桁)
        
        # ★★★ バグ修正 (Aボタンは Bit 0) ★★★
        0xA5, 0x06,  # LDA Controller_Trg
        0x29, 0x01,  # AND #%00000001
        0xF0, 0x0D,  # BEQ Result_End
        
        # A が押された -> Title へ移行
        0xA9, 0x00,
        0x85, 0x00,
        0x20, 0x80, 0xC2,
        0x85, 0x03, # カウントリセット
        0x85, 0x04,
        
    #Result_End:
        0x4C, 0xEF, 0xC1,  # JMP NMI_End

    #NMI_End: ($C1EF)
        0x68,        # PLA
        0xA8,        # TAY
        0x68,        # PLA
        0xAA,        # TAX
        0x68,        # PLA
        0x40,        # RTI
        
        # --- $C200: ReadController ---
        # ★★★ バグ修正 (読み取りロジック) ★★★
        # (A=Bit0, B=Bit1, Sel=Bit2, Sta=Bit3, U,D,L,R)
        0xA9, 0x01,  # LDA #$01
        0x8D, 0x16, 0x40,  # STA $4016 (ラッチ)
        0xA9, 0x00,  # LDA #$00
        0x8D, 0x16, 0x40,  # STA $4016
        
        0xA2, 0x08,  # LDX #$08 (8回ループ)
        0x85, 0x05,  # STA Controller_Raw (0 クリア)
    #ReadLoop ($C20A):
        0xAD, 0x16, 0x40,  # LDA $4016
        0x29, 0x01,  # AND #$01 (A = 0 or 1)
        0x85, 0x08,  # STA TempA
        
        0xA5, 0x05,  # LDA Controller_Raw
        0x0A,        # ASL A (左に1シフト)
        0x05, 0x08,  # ORA TempA (新しいビットを D0 に追加)
        0x85, 0x05,  # STA Controller_Raw
        
        0xCA,        # DEX
        0xD0, 0xF1,  # BNE ReadLoop ($C20A)
        0x60,        # RTS
        
        # $C21D からパディング (NOP)
        # ...
        
        # $C280: ClearVRAM_BG
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA,
        # $C280
        0xA9, 0x20, 0x8D, 0x06, 0x20, 0xA9, 0x00, 0x8D, 0x06, 0x20,
        0xA9, 0x10,
        0xA2, 0x03,  # LDX #$03 (3 ページ)
    #ClearBG_Page:
        0xA0, 0x00,  # LDY #$00
    #ClearBG_Byte:
        0x8D, 0x07, 0x20,  # STA $2007
        0xC8,        # INY
        0xD0, 0xFB,  # BNE ClearBG_Byte
        0xCA,        # DEX
        0xD0, 0xF7,  # BNE ClearBG_Page
    # (残り 192 バイト)
        0xA0, 0xC0,  # LDY #$C0
    #ClearBG_Rest:
        0x8D, 0x07, 0x20,  # STA $2007
        0x88,        # DEY
        0xD0, 0xFB,  # BNE ClearBG_Rest
        0x60,        # RTS
        
        # $C2A3 からパディング
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA, 0xEA,
        
        # --- $C300: DrawTextTitle ---
        0xA9, 0x21, 0x8D, 0x06, 0x20, 0xA9, 0x88, 0x8D, 0x06, 0x20, # PPU $2188
        0xA9, 0x00, 0x85, 0x0B, 0xA9, 0xE0, 0x85, 0x0C, # PTR $E000
        0xA0, 0x10, 0x88, 0x20, 0x00, 0xC4, 0x60, # LDY #16, DEY, JSR $C400
        
        # --- $C320: DrawTextCount ---
        0xA9, 0x21, 0x8D, 0x06, 0x20, 0xA9, 0x4A, 0x8D, 0x06, 0x20, # PPU $214A
        0xA9, 0x20, 0x85, 0x0B, 0xA9, 0xE0, 0x85, 0x0C, # PTR $E020
        0xA0, 0x06, 0x88, 0x20, 0x00, 0xC4, 0x60, # LDY #6, DEY, JSR $C400
        
        # --- $C340: DrawTextTime --- (アドレス修正 $C33B)
        0xA9, 0x20, 0x8D, 0x06, 0x20, 0xA9, 0xC8, 0x8D, 0x06, 0x20, # PPU $20C8
        0xA9, 0x40, 0x85, 0x0B, 0xA9, 0xE0, 0x85, 0x0C, # PTR $E040
        0xA0, 0x05, 0x88, 0x20, 0x00, 0xC4, 0x60, # LDY #5, DEY, JSR $C400
        
        # --- $C356: DrawSingleDigit --- (アドレス修正 $C356)
        0x85, 0x08, # STA TempA
        0xA9, 0x21, 0x8D, 0x06, 0x20, 0xA9, 0xD0, 0x8D, 0x06, 0x20, # PPU $21D0
        0xA5, 0x08, # LDA TempA
        0x8D, 0x07, 0x20, 0x60,
        
        # --- $C368: DrawTextTimeUp --- (アドレス修正 $C368)
        0xA9, 0x21, 0x8D, 0x06, 0x20, 0xA9, 0x8B, 0x8D, 0x06, 0x20, # PPU $218B
        0xA9, 0x60, 0x85, 0x0B, 0xA9, 0xE0, 0x85, 0x0C, # PTR $E060
        0xA0, 0x09, 0x88, 0x20, 0x00, 0xC4, 0x60, # LDY #9, DEY, JSR $C400
        
        # --- $C383: DrawNumber (3桁 @ $2151) --- (アドレス修正 $C383)
        0xA9, 0x21, 0x8D, 0x06, 0x20, 0xA9, 0x51, 0x8D, 0x06, 0x20, # PPU $2151
        0xA9, 0x00, 0x85, 0x0D,
    #Div100_Loop:
        0x38, 0xA5, 0x08, 0xE9, 0x64, 0x85, 0x08, 0xA5, 0x09, 0xE9, 0x00, 0x85, 0x09,
        0x90, 0x02, 0xE6, 0x0D, 0x4C, 0x8F, 0xC3, # JMP $C38F
    #Div100_Done:
        0x18, 0xA5, 0x08, 0x69, 0x64, 0x85, 0x08, 0xA5, 0x09, 0x69, 0x00, 0x85, 0x09,
        0xA5, 0x0D, 0x8D, 0x07, 0x20,
    # 10の位
        0xA9, 0x00, 0x85, 0x0D,
    #Div10_Loop:
        0x38, 0xA5, 0x08, 0xE9, 0x0A, 0x85, 0x08,
        0x90, 0x02, 0xE6, 0x0D, 0x4C, 0xB2, 0xC3, # JMP $C3B2
    #Div10_Done:
        0x18, 0xA5, 0x08, 0x69, 0x0A, 0x85, 0x08,
        0xA5, 0x0D, 0x8D, 0x07, 0x20,
    # 1の位
        0xA5, 0x08, 0x8D, 0x07, 0x20, 0x60,
        
        # --- $C3CF: DrawNumber (2桁 @ $20CE) --- (アドレス修正 $C3CF)
        0xA9, 0x20, 0x8D, 0x06, 0x20, 0xA9, 0xCE, 0x8D, 0x06, 0x20, # PPU $20CE
        0xA9, 0x00, 0x85, 0x0D,
    #Div10_Loop_B:
        0x38, 0xA5, 0x08, 0xE9, 0x0A, 0x85, 0x08,
        0x90, 0x02, 0xE6, 0x0D, 0x4C, 0xD8, 0xC3, # JMP $C3D8
    #Div10_Done_B:
        0x18, 0xA5, 0x08, 0x69, 0x0A, 0x85, 0x08,
        0xA5, 0x0D, 0x8D, 0x07, 0x20,
        0xA5, 0x08, 0x8D, 0x07, 20, 0x60,
        
        # --- $C400: DrawTextLoop ---
        0xB1, 0x0B,  # LDA (TempPtr_L),Y
        0x8D, 0x07, 0x20,  # STA $2007
        0x88,        # DEY
        0x10, 0xF9,  # BPL DrawTextLoop
        0x60,        # RTS
        
        # ($C408 まで)
    ]
    
    # --- PRG ROM にコードを書き込む ---
    # アドレスジャンプの再計算
    # StateTitle ($C129) -> JSR DrawSingleDigit ($C356)
    code[0x15D] = 0x56
    code[0x15E] = 0xC3
    # StateGame ($C18D) -> JSR DrawNumber 3桁 ($C383)
    code[0x19F] = 0x83
    code[0x1A0] = 0xC3
    # StateGame ($C18D) -> JSR DrawNumber 2桁 ($C3CF)
    code[0x1AA] = 0xCF
    code[0x1AB] = 0xC3
    # StateResult ($C1F3) -> JSR DrawNumber 3桁 ($C383)
    code[0x207] = 0x83
    code[0x208] = 0xC3

    # マシン語コードを PRG ROM の $C000 (オフセット 0) に書き込む
    prg_rom[0x0000 : 0x0000 + len(code)] = bytearray(code)
    
    # --- ベクタ (PRG ROM の最後) ---
    # $FFFA-$FFFB: NMI Vector -> $C100
    prg_rom[0x3FFA] = 0x00
    prg_rom[0x3FFB] = 0xC1
    # $FFFC-$FFFD: Reset Vector -> $C000
    prg_rom[0x3FFC] = 0x00
    prg_rom[0x3FFD] = 0xC0
    # $FFFE-$FFFF: IRQ Vector -> $C000 (使わない)
    prg_rom[0x3FFE] = 0x00
    prg_rom[0x3FFF] = 0xC0
    
    return prg_rom

# --- 3. iNES ヘッダ生成と ROM 書き出し ---

def write_nes_rom(output_path, prg_rom, chr_rom):
    print(f"ステップ 3: iNES ヘッダを生成し、'{output_path}' に書き出し中...")
    
    header = bytearray(16)
    header[0:4] = b'NES\x1A'
    header[4] = 1  # PRG ROM (16KB) x 1
    header[5] = 1  # CHR ROM (8KB) x 1
    header[6] = 0b00000000 # マッパー 0, 水平ミラーリング
    header[7] = 0b00000000 # マッパー 0
    
    try:
        with open(output_path, 'wb') as f:
            f.write(header)
            f.write(prg_rom)
            f.write(chr_rom)
    except Exception as e:
        print(f"エラー: ROM ファイル '{output_path}' の書き出しに失敗しました。 {e}", file=sys.stderr)
        return False
        
    print("---")
    print(f"✅ ビルド完了: {output_path}")
    print("---")
    return True

# --- メイン実行 ---

def main():
    if len(sys.argv) != 2:
        print(f"使い方: python {os.path.basename(sys.argv[0])} <出力.nes>", file=sys.stderr)
        sys.exit(1)
        
    output_file = sys.argv[1]
    
    chr_rom = generate_font_chr()
    if chr_rom is None:
        sys.exit(1)
        
    prg_rom = generate_prg_rom()
    if prg_rom is None:
        sys.exit(1)
        
    if not write_nes_rom(output_file, prg_rom, chr_rom):
        sys.exit(1)

if __name__ == "__main__":
    main()
